load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "completedactionlogger",
    srcs = ["server.go"],
    importpath = "github.com/buildbarn/bb-portal/internal/api/grpc/completedactionlogger",
    visibility = ["//:__subpackages__"],
    deps = [
        "//ent/gen/ent",
        "//ent/gen/ent/action",
        "//ent/gen/ent/bazelinvocation",
        "//ent/gen/ent/completedaction",
        "//ent/gen/ent/instancename",
        "//internal/database",
        "//internal/database/dbauthservice",
        "@bazel_remote_apis//build/bazel/remote/execution/v2:remote_execution_go_proto",
        "@com_github_buildbarn_bb_remote_execution//pkg/proto/completedactionlogger",
        "@com_github_buildbarn_bb_storage//pkg/util",
        "@com_github_google_uuid//:uuid",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//types/known/emptypb",
    ],
)
