package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"time"

	"github.com/buildbarn/bb-portal/ent/gen/ent"
	"github.com/buildbarn/bb-portal/ent/gen/ent/action"
	"github.com/buildbarn/bb-portal/ent/gen/ent/authenticateduser"
	"github.com/buildbarn/bb-portal/ent/gen/ent/bazelinvocation"
	"github.com/buildbarn/bb-portal/ent/gen/ent/build"
	"github.com/buildbarn/bb-portal/ent/gen/ent/instancename"
	"github.com/buildbarn/bb-portal/ent/gen/ent/invocationfiles"
	"github.com/buildbarn/bb-portal/ent/gen/ent/invocationtarget"
	"github.com/buildbarn/bb-portal/ent/gen/ent/target"
	"github.com/buildbarn/bb-portal/ent/gen/ent/testsummary"
	"github.com/buildbarn/bb-portal/internal/graphql/model"
	"github.com/google/uuid"
)

// Profile is the resolver for the profile field.
func (r *bazelInvocationResolver) Profile(ctx context.Context, obj *ent.BazelInvocation) (*model.Profile, error) {
	profile, err := obj.QueryInvocationFiles().Where(invocationfiles.NameEQ(obj.ProfileName)).Only(ctx)
	if err != nil {
		return nil, nil
	}

	if profile == nil || profile.Name == "" || profile.Digest == "" || profile.SizeBytes == 0 || profile.DigestFunction == "" {
		return nil, nil
	}

	return &model.Profile{
		Name:           profile.Name,
		Digest:         profile.Digest,
		SizeInBytes:    int(profile.SizeBytes),
		DigestFunction: profile.DigestFunction,
	}, nil
}

// HasFailedActions is the resolver for the hasFailedActions field.
func (r *bazelInvocationResolver) HasFailedActions(ctx context.Context, obj *ent.BazelInvocation) (bool, error) {
	return obj.QueryActions().
		Where(action.Success(false)).
		Exist(ctx)
}

// HasActionsForTarget is the resolver for the hasActionsForTarget field.
func (r *bazelInvocationResolver) HasActionsForTarget(ctx context.Context, obj *ent.BazelInvocation, targetID string) (bool, error) {
	targetLabel, err := targetLabelForID(ctx, r.db.Ent(), targetID)
	if err != nil {
		return false, err
	}
	return obj.QueryActions().
		Where(action.LabelEQ(targetLabel)).
		Exist(ctx)
}

// ActionsForTarget is the resolver for the actionsForTarget field.
func (r *bazelInvocationResolver) ActionsForTarget(ctx context.Context, obj *ent.BazelInvocation, targetID string) ([]*ent.Action, error) {
	targetLabel, err := targetLabelForID(ctx, r.db.Ent(), targetID)
	if err != nil {
		return nil, err
	}
	return obj.QueryActions().
		Where(action.LabelEQ(targetLabel)).
		All(ctx)
}

// TimeSinceLastConnectionMillis is the resolver for the timeSinceLastConnectionMillis field.
func (r *connectionMetadataResolver) TimeSinceLastConnectionMillis(ctx context.Context, obj *ent.ConnectionMetadata) (int, error) {
	return int(time.Since(obj.ConnectionLastOpenAt).Milliseconds()), nil
}

// GetAuthenticatedUser is the resolver for the getAuthenticatedUser field.
func (r *queryResolver) GetAuthenticatedUser(ctx context.Context, userUUID uuid.UUID) (*ent.AuthenticatedUser, error) {
	// CollectFields here is used to avoid the N+1 query problem. Ent shouldn't
	// need it, but somehow it does.
	query, err := r.db.Ent().AuthenticatedUser.Query().Where(authenticateduser.UserUUID(userUUID)).CollectFields(ctx)
	if err != nil {
		return nil, err
	}
	return query.First(ctx)
}

// GetBazelInvocation is the resolver for the getBazelInvocation field.
func (r *queryResolver) GetBazelInvocation(ctx context.Context, invocationID uuid.UUID) (*ent.BazelInvocation, error) {
	// CollectFields here is used to avoid the N+1 query problem. Ent shouldn't
	// need it, but somehow it does.
	query, err := r.db.Ent().BazelInvocation.Query().Where(bazelinvocation.InvocationID(invocationID)).CollectFields(ctx)
	if err != nil {
		return nil, err
	}
	return query.First(ctx)
}

// GetBuild is the resolver for the getBuild field.
func (r *queryResolver) GetBuild(ctx context.Context, buildUUID uuid.UUID) (*ent.Build, error) {
	// CollectFields here is used to avoid the N+1 query problem. Ent shouldn't
	// need it, but somehow it does.
	query, err := r.db.Ent().Build.Query().Where(build.BuildUUID(buildUUID)).CollectFields(ctx)
	if err != nil {
		return nil, err
	}
	return query.First(ctx)
}

// TestSummaryStats is the resolver for the testSummaryStats field.
func (r *queryResolver) TestSummaryStats(ctx context.Context, where *ent.TestSummaryWhereInput) (*model.TestSummaryStats, error) {
	query := r.db.Ent().TestSummary.Query()
	var err error
	if where != nil {
		query, err = where.Filter(query)
	}
	if err != nil {
		return nil, err
	}

	stats := &model.TestSummaryStats{}
	if stats.Tests, err = query.Clone().Count(ctx); err != nil {
		return nil, err
	}
	if stats.Passed, err = query.Clone().Where(testsummary.OverallStatus("PASSED")).Count(ctx); err != nil {
		return nil, err
	}
	if stats.Flaky, err = query.Clone().Where(testsummary.OverallStatus("FLAKY")).Count(ctx); err != nil {
		return nil, err
	}
	if stats.Incomplete, err = query.Clone().Where(testsummary.OverallStatus("INCOMPLETE")).Count(ctx); err != nil {
		return nil, err
	}
	if stats.Failed, err = query.Clone().
		Where(testsummary.OverallStatusIn("FAILED", "TIMEOUT", "REMOTE_FAILURE", "FAILED_TO_BUILD")).
		Count(ctx); err != nil {
		return nil, err
	}

	statusBuckets := stats.Passed + stats.Flaky + stats.Incomplete + stats.Failed
	stats.NoStatus = stats.Tests - statusBuckets
	if stats.NoStatus < 0 {
		stats.NoStatus = 0
	}

	if stats.Runs, err = sumTestSummaryInt32Field(ctx, query, testsummary.FieldRunCount); err != nil {
		return nil, err
	}
	if stats.Attempts, err = sumTestSummaryInt32Field(ctx, query, testsummary.FieldAttemptCount); err != nil {
		return nil, err
	}
	if stats.Cached, err = sumTestSummaryInt32Field(ctx, query, testsummary.FieldTotalNumCached); err != nil {
		return nil, err
	}
	return stats, nil
}

// GetTarget is the resolver for the getTarget field.
func (r *queryResolver) GetTarget(ctx context.Context, instanceName string, label string, aspect string, targetKind string) (*ent.Target, error) {
	// CollectFields here is used to avoid the N+1 query problem. Ent shouldn't
	// need it, but somehow it does.
	query, err := r.db.Ent().Target.Query().Where(
		target.LabelEQ(label),
		target.Aspect(aspect),
		target.TargetKind(targetKind),
		target.HasInstanceNameWith(
			instancename.Name(instanceName),
		),
	).CollectFields(ctx)
	if err != nil {
		return nil, err
	}
	return query.First(ctx)
}

// InvocationTargetsTotalDurationMillis is the resolver for the invocationTargetsTotalDurationMillis field.
func (r *targetResolver) InvocationTargetsTotalDurationMillis(ctx context.Context, obj *ent.Target) (int, error) {
	// If there are no invocation targets with a duration, SUM in SQL yields NULL
	// which can cause a scan error. Count first and return 0 if no rows match.
	count, err := obj.QueryInvocationTargets().
		Where(invocationtarget.DurationInMsNotNil()).
		Count(ctx)
	if err != nil {
		return 0, err
	}
	if count == 0 {
		return 0, nil
	}

	return obj.QueryInvocationTargets().
		Where(invocationtarget.DurationInMsNotNil()).
		Aggregate(ent.Sum(invocationtarget.FieldDurationInMs)).
		Int(ctx)
}
