// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: action_analytics.sql

package sqlc

import (
	"context"
	"time"
)

const claimActionAnalytics = `-- name: ClaimActionAnalytics :one
WITH candidate AS (
    SELECT id
    FROM bazel_invocations
    WHERE bep_completed = true
      AND (
        action_analytics_state = 'PENDING'
        OR (
          action_analytics_state = 'PROCESSING'
          AND (
            action_analytics_started_at IS NULL
            OR action_analytics_started_at < $1::timestamptz
          )
        )
      )
    ORDER BY ended_at NULLS LAST, id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE bazel_invocations AS invocation
SET action_analytics_state = 'PROCESSING',
    action_analytics_started_at = NOW(),
    action_analytics_completed_at = NULL,
    action_analytics_failure_message = NULL,
    action_analytics_result = NULL
FROM candidate
WHERE invocation.id = candidate.id
RETURNING invocation.id
`

func (q *Queries) ClaimActionAnalytics(ctx context.Context, staleBefore time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, claimActionAnalytics, staleBefore)
	var id int64
	err := row.Scan(&id)
	return id, err
}
